---
- name: Generate netplan
  ansible.builtin.command: netplan generate
  become: true

- name: Recreate initial ramdisk
  ansible.builtin.command: mkinitcpio -P
  become: true

- name: Reinstall grub
  ansible.builtin.command: "{{ vmhost_grub_mkconfig_command }} -o {{ vmhost_grub_boot_conf_dest }}"
  become: true

- name: Reboot system
  ansible.builtin.reboot:
  become: true
