---
- name: recreate_initial_ramdisk
  ansible.builtin.command: mkinitcpio -P 

- name: reinstall_grub
  ansible.builtin.command: "{{grub-mkconfig}} -o {{grub_boot_conf_dest}}"

- name: reboot_system
  ansible.builtin.reboot:
