---
# - name: Set OS distribution dependent variables
#   include_vars: "os_{{ ansible_facts['distribution'] }}.yml"

- name: Install packages
  ansible.builtin.package:
    name: 
      - easytag 
    state: present
  tags:
    - packages

- name: Add ABCDE config
  ansible.builtin.copy:
    src: abcde.conf
    dest: /home/{{ remote_user.name }}/.abcde.conf
    owner: "{{ remote_user.name }}"
    group: "{{ remote_user.group }}"
    backup: yes

# - name: Install AUR pacakges
#   kewlfft.aur.aur:
#     name: 
#       - 
#     state: present
#   tags:
#     - aur
#     - packages
#   become: "yes"
#   become_user: "{{ aur.builder }}"
#   when: ansible_facts['distribution'] == "Archlinux"

# - name: Configure 
#   ansible.builtin.template:
#     src: 
#     dest: /
#     backup: true
#   notify: 

# - name: Create file
#   ansible.builtin.copy:
#     src: 
#     dest: /
#     backup: true
#   notify: 

# - include_tasks: .yml
#   when: ansible_facts['distribution'] == "DistroName"
