---
# Run the following commands on localhost
#   pacman -S git ansible
#   nano ~/.vault_pass.txt
#   chmod 600 ~/.vault_pass.txt
#   ansible-galaxy install geerlingguy.ntp geerlingguy.docker
#   ansible-galaxy collection install kewlfft.aur
#   ansible-pull --vault-password-file ~/.vault_pass.txt -U http://github.com/WittFan0/ansible.git

- hosts: archvm
  connection: local
  
  # vars_prompt:
  #   - name: hostname
  #     prompt: What is the name of this computer?
  #     private: false

  pre_tasks:
    - name: Classify hosts depending on their OS distribution
      group_by:
        key: os_{{ ansible_facts['distribution'] }}

  roles:
    - common
    - geerlingguy.ntp
    - monitor
    - harden  # TODO: Limit to WAN interface
    - dnsmasq
    - geerlingguy.docker
    - mediasrv
    - geerlingguy.docker
    - collab
    - sound
    - xfce4
    - multimedia
    - development
    - graphics
    - vmhost

  become_user: "{{ remote_user.name }}"
  environment:
    DBUS_SESSION_BUS_ADDRESS: unix:path=/run/user/{{ remote_user.uid }}/bus
  roles: 
    - xfce4-customize

  post_tasks:
    - name: Disable ssh root logins and limit other logins to key-based
      become: true
      roles:
        - sshd-keyonly
