---
- hosts: localhost
  connection: local
  become: true

  pre_tasks:
    - name: Update package cache and upgrade (arch)
      community.general.pacman:
        update_cache: true
        upgrade: true
      tags:
        - packages
      when: ansible_facts['distribution'] == "Archlinux"

    - name: Update package cache and upgrade (debian)
      ansible.builtin.apt: 
        update_cache: yes
        cache_valid_time: 3600  # Only run "update_cache=yes" if the last one is more than 3600 seconds ago
        name: "*"
        state: latest
        autoclean: yes
        autoremove: yes
      tags:
        - packages
      when: ansible_facts['distribution'] in ["Debian", "Ubuntu"]

  tasks:
    - name: Classify hosts depending on their OS distribution
      group_by:
        key: os_{{ ansible_facts['distribution'] }}

#   roles:
#     - common
#     - sshd-keyonly
#     - geerlingguy.ntp
#     - monitor
#     - harden  # TODO: Limit to WAN interface

# - hosts: router
#   roles:
#     - dnsmasq

# - hosts: media_server
#   roles:
#     - geerlingguy.docker
#     - mediasrv

# - hosts: collab_server
#   roles:
#     - geerlingguy.docker
#     - collab

# - hosts: workstation
#   roles:
#     - sound
#     - xfce4
#     - multimedia
#     - development
#     - graphics

# - hosts: vmhost
#   roles:
#     - vmhost

# - hosts: workstation
#   become_user: "{{ remote_user.name }}"
#   environment:
#     DBUS_SESSION_BUS_ADDRESS: unix:path=/run/user/{{ remote_user.uid }}/bus
#   roles: 
#     - xfce4-customize

