---
# Run the following commands on localhost
#   pacman -S git ansible
#   nano ~/.vault_pass.txt
#   chmod 600 ~/.vault_pass.txt
#   ansible-galaxy install geerlingguy.ntp geerlingguy.docker
#   ansible-galaxy collection install kewlfft.aur
#   ansible-pull --vault-password-file ~/.vault_pass.txt -U http://github.com/WittFan0/ansible.git

- hosts: archvm
  connection: local
  environment:
    http_proxy: http://dan:3128
    https_proxy: http://dan:3128
    ftp_proxy: http://dan:3128

  # vars_prompt:
  #   - name: hostname
  #     prompt: What is the name of this computer?
  #     private: false

  pre_tasks:
    - name: Classify hosts depending on their OS distribution
      group_by:
        key: os_{{ ansible_facts['distribution'] }}

  roles:
    - update
    - common
    # - geerlingguy.ntp
    # - monitor
    # - harden  # TODO: Limit to WAN interface
    # - dnsmasq
    # - geerlingguy.docker
    # - mediasrv
    # - geerlingguy.docker
    # - collab
    # - desktopenv
    # - ripping
    # - development
    # - graphics
    # - vmhost
    # - gaming
    # - snapper
    # - sshd-keyonly  # <-- Must come last because it disables root ssh

  post_tasks:
    - name: Remove sudo-less pacman permission for `aur_builder`
      ansible.builtin.file:
        path: /etc/sudoers.d/11-install-aur_builder
        state: absent
      tags:
        - aur
        - packages
      when: ansible_facts['distribution'] == "Archlinux"

    - name: Remove 'aur_builder' user
      ansible.builtin.user:
        name: "{{ aur.builder }}"
        state: absent
        remove: yes
      when: ansible_facts['distribution'] == "Archlinux"
      