---
# - name: Set OS distribution dependent variables
#   ansible.builtin.include_vars: "os_{{ ansible_facts['distribution'] }}.yml"

- hosts: archvm
  # connection: local
  become: true
  become_user: "{{ my_remote_user.name }}"
  tasks:
    - name: Create ansible project directory if it does not exist
      ansible.builtin.file:
        path: /home/{{ my_remote_user.name }}/Projects/ansible
        state: directory
        owner: "{{ my_remote_user.name }}"
        group: "{{ my_remote_user.group }}"
        mode: '0755'
        recurse: true

    - name: Checkout ansible project from github
      ansible.builtin.git:
        repo: https://github.com/WittFan0/ansible.git
        dest: /home/{{ my_remote_user.name }}/Projects/ansible

    - name: Create myscripts project directory if it does not exist
      ansible.builtin.file:
        path: /home/{{ my_remote_user.name }}/Projects/myscripts
        state: directory
        owner: "{{ my_remote_user.name }}"
        group: "{{ my_remote_user.group }}"
        mode: '0755'
        recurse: true

    - name: Checkout myscripts from github
      ansible.builtin.git:
        repo: https://github.com/WittFan0/myscripts.git
        dest: /home/{{ my_remote_user.name }}/Projects/myscripts
