---
- hosts: all
  become: true

  pre_tasks:
    - name: Classify hosts depending on their OS distribution
      group_by:
        key: os_{{ ansible_facts['distribution'] }}

  roles:
    - common
    - sshd-keyonly
    - geerlingguy.ntp
    - monitor
    - harden  # TODO: Limit to WAN interface

- hosts: router
  become: true
  roles:
    - dnsmasq

- hosts: media_server
  become: true
  roles:
    - geerlingguy.docker
    - mediasrv
    # - harden  # TODO: Limit to WAN interface

- hosts: collab_server
  become: true
  roles:
    - geerlingguy.docker
    - collab

- hosts: workstation
  become: true
  roles:
    - sound
    - xfce4
    - multimedia
    - development
    - graphics

- hosts: vmhost
  become: true
  roles:
    - vmhost

- hosts: workstation
  become: true
  become_user: "{{ remote_user.name }}"
  environment:
    DBUS_SESSION_BUS_ADDRESS: unix:path=/run/user/{{ remote_user.uid }}/bus
  roles: 
    - xfce4-customize

