---
- hosts: all
  become: true

  environment:
    http_proxy: http://dan:3128
    https_proxy: http://dan:3128
    ftp_proxy: http://dan:3128

  pre_tasks:
    - name: Classify hosts depending on their OS distribution
      group_by:
        key: os_{{ ansible_facts['distribution'] }}

  roles:
    - update
    - common
    - geerlingguy.ntp
    - monitor
    - harden  # TODO: Limit to WAN interface

- hosts: router
  become: true
  roles:
    - dnsmasq

- hosts: proxy
  become: true
  roles:
    - proxy

- hosts: media_server
  become: true
  roles:
    - geerlingguy.docker
    - mediasrv

- hosts: collab_server
  become: true
  roles:
    - geerlingguy.docker
    - collab

- hosts: workstation
  become: true
  roles:
    - desktopenv
    # - multimedia
    - development
    - graphics

- hosts: development
  become: true
  roles:
    - development

- hosts: gaming
  become: true
  roles:
    - gaming

- hosts: vmhost
  become: true
  roles:
    - vmhost

- hosts: all
  become: true
  tasks:
    - name: Go back to downloading db sigs
      ansible.builtin.lineinfile:
        path: /etc/pacman.conf
        regexp: '^SigLevel'
        line: SigLevel = Required DatabaseNever
        insertafter: '^\[options\]'
        backup: true
      tags:
        - packages
      when: ansible_facts['distribution'] == "Archlinux"

- hosts: btrfs
  become: true
  roles:
    - snapper

# - hosts: all
#   become: true
#   roles:
#     - sshd-keyonly  # <-- Must come last because it disables root ssh
