- name: Set OS distribution dependent variables
  ansible.builtin.include_vars: "os_{{ ansible_facts['distribution'] }}.yml"

- name: Install Gnome packages
  ansible.builtin.package:
    name: "{{ gnome_packages }}"
    state: present
    update_cache: true
  tags:
    - packages
  environment: "{{proxy_env}}"

- name: Install Gnome AUR pacakges
  kewlfft.aur.aur:
    name: "{{ gnome_packages_aur }}"
    state: present
  tags:
    - aur
    - packages
  become: true
  become_user: "{{ aur.builder }}"
  when: ansible_facts['distribution'] == "Archlinux"
  environment: "{{proxy_env}}"

