---
  # This play executes in the directory it is called from. Since this play is included by other plays,
  # all file references in this play must redirect to the desktopenv path.

- name: Set OS distribution dependent variables
  ansible.builtin.include_vars: "../../desktopenv/vars/os_{{ ansible_facts['distribution'] }}.yml"

- name: Install KDE packages
  ansible.builtin.package:
    name: "{{ desktopenv_kde_packages }}"
    state: present
  tags:
    - packages
  environment: "{{ proxy_env }}"
  when: desktop_environment == "kde"

- name: Setup a user to build AUR packages
  ansible.builtin.include_tasks: ../../common/tasks/aur.yml
  when: ansible_facts['distribution'] == "Archlinux" and aur_ran is not defined and desktop_environment == "kde"

- name: Install KDE AUR pacakges
  kewlfft.aur.aur:
    name: "{{ desktopenv_kde_packages_aur }}"
    state: present
  tags:
    - aur
    - packages
  become: true
  become_user: "{{ aur.builder }}"
  when: ansible_facts['distribution'] == "Archlinux" and desktop_environment == "kde"
  environment: "{{ proxy_env }}"

- name: Create settings file for kdesu if it doesn't exist
  ansible.builtin.file:
    path: /home/{{ remote_user.name }}/.config/
    state: directory
    owner: "{{ remote_user.name }}"
    group: "{{ remote_user.group }}"
    mode: '0755'
    recurse: false
  when: desktop_environment == "kde"

- name: Have kdesu use sudo instead of su
  ansible.builtin.copy:
    content: |
      [super-user-command]
      super-user-command=sudo
    dest: /home/{{ remote_user.name }}/.config/kdesurc
    mode: '0644'
    owner: "{{ remote_user.name }}"
    group: "{{ remote_user.group }}"
    backup: true
  when: desktop_environment == "kde"

# *** SDDP support for Wayland is not yet fully functional ***

- name: Create SSDM config directory if it doesn't exist
  ansible.builtin.file:
    path: /etc/sddm.conf.d/
    state: directory
    mode: '0755'
  when: desktop_environment == "kde"

- name: Configure SDDM to use Wayland
  ansible.builtin.copy:
    content: |
      [General]
      DisplayServer=wayland
      GreeterEnvironment=QT_WAYLAND_SHELL_INTEGRATION=layer-shell

      [Wayland]
      CompositorCommand=kwin_wayland --no-lockscreen --no-kactivities --no-global-shortcuts --lock --drm --locale1
    dest: /etc/sddm.conf.d/10-wayland.conf
    mode: '0644'
    backup: false
  when: desktop_environment == "kde"
