---
- name: Set OS distribution dependent variables
  include_vars: "os_{{ ansible_facts['distribution'] }}.yml"

- name: Install sound system
  ansible.builtin.package:
    name:
      - wireplumber
      - pipewire-pulse
      # - pavucontrol
      - pipewire-jack
      # - lib32-pipewire-jack
    state: present
  environment: "{{proxy_env}}"

- name: Install XFCE desktop environment
  ansible.builtin.include_tasks: xfce.yml
  when: desktop_environment == "xfce"

- name: Install KDE desktop environment
  ansible.builtin.include_tasks: kde.yml
  when: desktop_environment == "kde"

- name: Install Gnome desktop environment
  ansible.builtin.include_tasks: gnome.yml
  when: desktop_environment == "gnome"

- name: Install virtio video packages
  ansible.builtin.package:
    name: "{{ virtio_video_packages }}"
    state: present
  tags:
    - packages
  when: ansible_facts['virtualization_role'] == "guest"
  environment: "{{proxy_env}}"

- name: Install nvidia video packages
  ansible.builtin.package:
    name: "{{ nvidia_video_packages }}"
    state: present
  tags:
    - packages
  when: ansible_facts['virtualization_role'] != "guest"
  environment: "{{proxy_env}}"

- name: Enable Lightdm display manager
  service:
    name: lightdm.service
    enabled: yes
    state: started
  when: desktop_environment == "xfce"

- name: Enable SDDM display manager
  service:
    name: sddm.service
    enabled: yes
    state: started
  when: desktop_environment == "kde"

- name: Enable Gnome display manager
  service:
    name: gdm.service
    enabled: yes
    state: started
  when: desktop_environment == "gnome"

