- name: Set OS distribution dependent variables
  ansible.builtin.include_vars: "os_{{ ansible_facts['distribution'] }}.yml"

- name: Install Sway packages
  ansible.builtin.package:
    name: "{{ sway_packages }}"
    state: present
  tags:
    - packages
  environment: "{{proxy_env}}"

# - name: Install Sway AUR pacakges
#   kewlfft.aur.aur:
#     name: "{{ sway_packages_aur }}"
#     state: present
#   tags:
#     - aur
#     - packages
#   become: true
#   become_user: "{{ aur.builder }}"
#   when: ansible_facts['distribution'] == "Archlinux"
#   environment: "{{proxy_env}}"