- name: Set OS distribution dependent variables
  include_vars: "os_{{ ansible_facts['distribution'] }}.yml"

- name: Install packages
  ansible.builtin.package:
    name: "{{ xfce_packages }}"
    state: present
    update_cache: true
  tags:
    - packages
  environment: "{{proxy_env}}"

- name: Install XFCE AUR pacakges
  kewlfft.aur.aur:
    name: "{{ xfce_packages_aur }}"
    state: present
  tags:
    - aur
    - packages
  become: true
  become_user: "{{ aur.builder }}"
  when: ansible_facts['distribution'] == "Archlinux"
  environment: "{{proxy_env}}"

- name: Install XFCE4 Gradient-black theme
  ansible.builtin.unarchive:
    src: Gradient-black-46.1.tar.gz
    dest: /usr/share/themes/

- name: Install EFDark-IconsCream icon theme
  ansible.builtin.unarchive:
    src: EFDark-IconsCream.tar.gz
    dest: /usr/share/icons/

- name: Set greeter GTK theme
  ansible.builtin.lineinfile:
    dest: /etc/lightdm/lightdm-gtk-greeter.conf
    insertafter: "[greeter]"
    regexp: "^theme-name"
    line: "theme-name = Gradient-black-46"

- name: Set greeter GTK icon theme
  ansible.builtin.lineinfile:
    dest: /etc/lightdm/lightdm-gtk-greeter.conf
    insertafter: "[greeter]"
    regexp: "^icon-theme-name"
    line: "icon-theme-name = EFDark-IconsCream"

- name: Set greeter GTK background
  ansible.builtin.lineinfile:
    dest: /etc/lightdm/lightdm-gtk-greeter.conf
    insertafter: "[greeter]"
    regexp: "^background"
    line: "background = /usr/share/backgrounds/xfce/XFCE_83_No_Logo.png"

