---
- name: Set OS distribution dependent variables
  ansible.builtin.include_vars: "os_{{ ansible_facts['distribution'] }}.yml"

- name: Install multimedia tools and players 
  become: true
  ansible.builtin.package:
    name: "{{ mm_packages }}"
    state: present
  tags:
    - packages

- name: Install abcde (apt)
  become: true
  ansible.builtin.apt:
    name: 
      - abcde
    state: present
  tags:
    - packages
  when: ansible_facts['distribution'] in ["Debian", "Ubuntu"]
  environment: "{{proxy_env}}"

# - name: Install abcde (AUR)  # <-- cant install key for cd-discid dependency
#   kewlfft.aur.aur:
#     name: 
#       - abcde
#     state: present
#   tags:
#     - aur
#     - packages
#   become: true
#   become_user: "{{ aur.builder }}"
#   when: ansible_facts['distribution'] == "Archlinux"

- name: Add ABCDE config
  ansible.builtin.copy:
    src: abcde.conf
    dest: /home/{{ remote_user.name }}/.abcde.conf
    owner: "{{ remote_user.name }}"
    group: "{{ remote_user.group }}"
    backup: true

