#!/bin/sh

# Exit immediately if a command exits with a non-zero status
set -e

# Test whether curl exists and is executable.
[ -x /usr/bin/curl ] || exit 0

sleep_then_download() {
# Sleep for up to an hour to spread the load of checking for updates
/usr/bin/sleep $(/usr/bin/shuf -i 1-3600 -n 1)
echo "Downloading DNS blacklist" | systemd-cat -t dnsmasq-blacklist-update -p info
/usr/bin/curl -o /etc/dnsmasq.blacklist.txt https://big.oisd.nl/dnsmasq2
}

sleep_then_download &
