---
- name: restart_grub-btrfs-snapper
  ansible.builtin.service:
    name: grub-btrfs-snapper.service
    state: restarted

- name: restart_snapper
  ansible.builtin.service:
    name: snapperd.service
    state: restarted

- name: reload_systemd_config
  ansible.builtin.command: systemctl daemon-reload