---
- name: restart_pulse_as_user
  ansible.builtin.systemd:
    name: pipewire-pulse.service
    scope: user
    state: restarted
  become: yes
  become_user: "{{ remote_user.name }}"
  environment:
    XDG_RUNTIME_DIR: "/run/user/{{ remote_user.uid }}"
