virtualization_packages:
  - iptables-nft
  - dnsmasq
  - dmidecode
  - gettext
  - virt-manager
  - vagrant
  - qemu-desktop
  - edk2-ovmf

grub_boot_conf_dest: '/boot/grub/grub.cfg'
grub_mkconfig_command: 'grub-mkconfig'