ansible_python_interpreter: /usr/bin/python3

remote_user:
    name: lance
    uid: 1000
    group: lance
    shell: bash
    shell_path: /usr/bin/bash
    email:  lancestyles1@gmail.com
    password: "{{ vault_user_password }}"

lan:
    domain: q.qw
    subnet: 192.168.40.0/24
    base: 192.168.40

lan_base: "{{ lan.subnet | regex_replace('.0/[0-9]{2}', '') }}"

mailer_passwd: "{{ vault_mailer_passwd }}"

google_client_secret: "{{ vault_google_client_secret }}"

docker_users:
    - lance

