ansible_python_interpreter: /usr/bin/python3

remote_user:
  name: lance
  # uid: 1000
  group: lance
  shell: bash
  shell_path: /bin/bash  # <-- This must have a matching entry in /etc/shells

lan:
  domain: r.qw
  subnet: 192.168.2.0/24
  gateway: 192.168.40.1
  base: 192.168.2

lan_base: "{{ lan.subnet | regex_replace('.0/[0-9]{2}', '') }}"

docker_users:
  - lance

proxy_env: http://dan:3128
