---
- name: restart_lightdm
  service:
    name: lightdm.service
    state: restarted

- name: restart_sddm
  service:
    name: sddm.service
    state: restarted

- name: recreate_initial_ramdisk
  command: mkinitcpio -P 

