---
- name: Set OS distribution dependent variables
  ansible.builtin.include_vars: "os_{{ ansible_facts['distribution'] }}.yml"

- name: Open printer administration port
  become: true
  community.general.ufw:
    rule: allow
    from_ip: "{{ lan.subnet }}"
    to_ip: "{{ lan0.ip }}"
    to_port: ipp
    comment: CUPS

- name: Install print system
  ansible.builtin.package:
    name: "{{ printing_packages }}"
    state: present
    update_cache: true
  tags:
    - packages

- name: Configure print system
  ansible.builtin.template:
    src: cupsd_conf.j2
    dest: /etc/cups/cupsd.conf
    mode: '0644'
    backup: true
  notify: Restart cups

- name: Setup a user to build AUR packages
  ansible.builtin.include_tasks: ../../common/tasks/aur.yml
  when: ansible_facts['distribution'] == "Archlinux" and aur_ran is not defined

- name: Install Brother printer driver (Arch) # <-- Doesn't work for printing to Brother printer over network. Use IPP instead.
  kewlfft.aur.aur:
    name:
      - brother-hll2320d
    state: present
  tags:
    - aur
    - packages
  become: true
  become_user: "{{ aur.builder }}"
  when: ansible_facts['distribution'] == "Archlinux"

# # These pacakges won't install becasue they are for an i386 architecture
# - name: Install hll2320dlpr package from the internet (Debian)
#   ansible.builtin.apt:
#     deb: https://download.brother.com/pub/com/linux/linux/packages/hll2320dlpr-3.2.0-1.i386.deb

# - name: Install hll2320dcupswrapper package from the internet (Debian)
#   ansible.builtin.apt:
#     deb: https://download.brother.com/pub/com/linux/linux/packages/hll2320dcupswrapper-3.2.0-1.i386.deb

- name: Get Brother printer driver (Debian)
  ansible.builtin.unarchive:
    src: linux-brprinter-installer-2.2.3-1.tar.gz
    dest: /opt
  when: ansible_facts['distribution'] in ["Debian", "Ubuntu"]

- name: Check for printer driver install file
  ansible.builtin.stat:
    path: /opt/linux-brprinter-installer-2.2.3-1.tar.gz
  register: register_brprinter_installer
- name: Report missing printer install file
  ansible.builtin.debug:
    msg: "The printer install file is missing"
  when: not register_brprinter_installer.stat.exists
- name: Make Brother printer driver installer file executable (Debian)
  ansible.builtin.file:
    path: /opt/linux-brprinter-installer-2.2.3-1
    mode: '0755'
  when: ansible_facts['distribution'] in ["Debian", "Ubuntu"] and register_brprinter_installer.stat.exists

# # Because the installation script is interactive,
# # it cannot be run using ansible.
# - name: Install Brother printer driver (Debian)
#   ansible.builtin.command: |
#     /opt/linux-brprinter-installer-2.2.3-1 HL-L2320D
#   when: ansible_facts['distribution'] in ["Debian", "Ubuntu"]

- name: Enable print system
  ansible.builtin.service:
    name: cups.service
    enabled: true
    state: started
