---
- name: Set OS distribution dependent variables
  ansible.builtin.include_vars: "os_{{ ansible_facts['distribution'] }}.yml"

- name: Install KDE dependency packages
  ansible.builtin.package:
    name: "{{ kde_dependency_packages }}"
    state: present
  tags:
    - packages
  when: desktop_environment == "kde"
  environment: "{{proxy_env}}"

- name: Install Gnome dependency packages
  ansible.builtin.package:
    name: "{{ gnome_dependency_packages }}"
    state: present
  tags:
    - packages
  when: desktop_environment == "gnome"
  environment: "{{proxy_env}}"

- name: Install gtk dependency packages
  ansible.builtin.package:
    name: "{{ gtk_dependency_packages }}"
    state: present
  tags:
    - packages
  when: desktop_environment == "xfce"
  environment: "{{proxy_env}}"

- name: Install packages
  ansible.builtin.package:
    name: 
      - ttf-liberation
      - vulkan-icd-loader
      - lib32-vulkan-icd-loader
      - steam
      - lib32-systemd
      - timidity++
      - freepats-general-midi
      - soundfont-fluid
      - lib32-gnutls
      - gamemode
      - gvfs
      - innoextract
      - lib32-gamemode
      - lib32-libva
      - lib32-libcanberra
      - lib32-vkd3d
      - vkd3d
      - xorg-xgamma
    state: present
  tags:
    - packages
  environment: "{{proxy_env}}"

- name: Install Lutris (pacman)
  ansible.builtin.package:
    name:  # <-- Wine dependencies listed on Lutris github page
      - lutris  # <-- Lutris is a Gnome package
      - wine-staging
      - wine-mono
      - wine-gecko
      - giflib
      - lib32-giflib
      - libpng
      - lib32-libpng
      - libldap
      - lib32-libldap
      - gnutls
      - lib32-gnutls
      - mpg123
      - lib32-mpg123
      - openal
      - lib32-openal
      - v4l-utils
      - lib32-v4l-utils
      - libpulse
      - lib32-libpulse
      - libgpg-error
      - lib32-libgpg-error
      - alsa-plugins
      - lib32-alsa-plugins
      - alsa-lib
      - lib32-alsa-lib
      - libjpeg-turbo
      - lib32-libjpeg-turbo
      - sqlite
      - lib32-sqlite
      - libxcomposite
      - lib32-libxcomposite
      - libxinerama
      - lib32-libgcrypt
      - libgcrypt
      - lib32-libxinerama
      - ncurses
      - lib32-ncurses
      - ocl-icd
      - lib32-ocl-icd
      - libxslt
      - lib32-libxslt
      - libva
      - lib32-libva
      - gtk3
      - lib32-gtk3
      - gst-plugins-base-libs
      - lib32-gst-plugins-base-libs
      - vulkan-icd-loader
      - lib32-vulkan-icd-loader
      - gnome-desktop  # <-- fetch screen resolutions on Wayland, used as a xrandr replacement (THIS IS NOT FULL GNOME ENV)
      - python-moddb
    state: present
  tags:
    - packages
  when: ansible_facts['distribution'] == "Archlinux"
  environment: "{{proxy_env}}"

- name: Install Lutris (apt)
  become: true
  ansible.builtin.apt:
    name:
      - lutris
      - python3-yaml
      - python3-requests
      - python3-pil
      - python3-gi
      - python3-gi-cairo
      - gir1.2-gtk-3.0
      - gir1.2-gnomedesktop-3.0  # <-- fetch screen resolutions on Wayland, used as a xrandr replacement (THIS IS NOT FULL GNOME ENV)
      - gir1.2-webkit2-4.0
      - gir1.2-notify-0.7
      - psmisc
      - cabextract
      - unzip
      - p7zip
      - curl
      - fluid-soundfont-gs
      # - x11-xserver-utils
      - python3-evdev
      - libc6-i386
      - lib32gcc1
      - libgirepository1.0-dev
      - python3-setproctitle
      - python3-distro
      - wine64  # <-- Wine dependencies listed on Lutris github page
      - wine32
      - libasound2-plugins:i386
      - libsdl2-2.0-0:i386
      - libdbus-1-3:i386
      - libsqlite3-0:i386
    state: present
  tags:
    - packages
  when: ansible_facts['distribution'] in ["Debian", "Ubuntu"]

- name: Install AUR pacakges
  kewlfft.aur.aur:
    name: 
      - dosbox-staging  # <-- Requires qt6. Is is worth it?
      - heroic-games-launcher-bin
      - gamehub
    state: present
  tags:
    - aur
    - packages
  become: true
  become_user: "{{ aur.builder }}"
  when: ansible_facts['distribution'] == "Archlinux"
  environment: "{{proxy_env}}"
