---
# - name: Set OS distribution dependent variables
#   include_vars: "os_{{ ansible_facts['distribution'] }}.yml"

- name: Install packages
  ansible.builtin.package:
    name: 
      - vulkan-icd-loader
      - lib32-vulkan-icd-loader
      - nvidia-utils
      - lib32-nvidia-utils
      - steam
      - ttf-liberation
      - lib32-systemd
      - timidity++
      - freepats-general-midi
      - soundfont-fluid
    state: present
  tags:
    - packages

- name: Install AUR pacakges
  kewlfft.aur.aur:
    name: 
      - dosbox-staging
    state: present
  tags:
    - aur
    - packages
  become: "yes"
  become_user: "{{ aur.builder }}"
  when: ansible_facts['distribution'] == "Archlinux"

# - name: Configure 
#   ansible.builtin.template:
#     src: 
#     dest: /
#     backup: true
#   notify: 

# - name: Create file
#   ansible.builtin.copy:
#     src: 
#     dest: /
#     owner: "{{ remote_user.name }}"
#     group: "{{ remote_user.group }}"
#     backup: true
#   notify: 

# - name: Enable and start service
#   service:
#     name: .service
#     enabled: yes
#     state: started

# - include_tasks: .yml
#   when: ansible_facts['distribution'] == "DistroName"
