- name: restart_dnsmasq
  ansible.builtin.service:
    name: dnsmasq.service
    state: restarted

- name: restart_resolved
  ansible.builtin.service:
    name: systemd-resolved.service
    state: restarted

