---
- name: Set OS distribution dependent variables
  include_vars: "os_{{ ansible_facts['distribution'] }}.yml"

- name: Install development packages
  become: true
  ansible.builtin.package:
    name: "{{ base_dev_packages }}"
    state: present
  tags:
    - packages

- name: Install code editor (Arch)
  become: true
  ansible.builtin.package:
    name: 
      - code
      - x11-ssh-askpass
    state: present
  tags:
    - packages
  when: ansible_facts['distribution'] == "Archlinux"

- name: Install VS Code dependencies (apt)
  become: true
  ansible.builtin.apt:
    name:
      - ca-certificates
      - apt-transport-https
      - gconf2
      - libasound2
      - libgtk2.0-0
      - libxss1
      - libxcb-dri3-0
      - libdrm2
      - libgbm1
      - libxshmfence1
    state: present
  tags:
    - packages
  when: ansible_facts['distribution'] in ["Debian", "Ubuntu"]

- name: Create APT keyrings dir
  become: true
  ansible.builtin.file:
    path: '/etc/apt/trusted.gpg.d/'
    state: directory
    mode: '0755'
  tags:
    - packages
  when: ansible_facts['distribution'] in ["Debian", "Ubuntu"]

- name: Install VS Code key (apt)
  become: true
  ansible.builtin.get_url:
    url: '{{ visual_studio_code_mirror }}/keys/microsoft.asc'
    dest: '/etc/apt/trusted.gpg.d/'
    mode: '0644'
    force: yes
  tags:
    - packages
  when: ansible_facts['distribution'] in ["Debian", "Ubuntu"]

- name: Install VS Code repo (apt)
  become: true
  ansible.builtin.apt_repository:
    repo: deb {{ visual_studio_code_mirror }}/repos/vscode stable main
    filename: vscode
    state: present
  tags:
    - packages
  when: ansible_facts['distribution'] in ["Debian", "Ubuntu"]

- name: Install VS Code (apt)
  become: true
  ansible.builtin.apt:
    name: code
    state: present
  tags:
    - packages
  when: ansible_facts['distribution'] in ["Debian", "Ubuntu"]

