---
# # Not needed. Using UFW sysctl instead.
# - name: update_sysctl
#   become: true
#   ansible.builtin.command: sysctl -p

- name: Generate netplan
  become: true
  ansible.builtin.command: netplan generate
