---
- name: Set OS distribution dependent variables
  include_vars: "os_{{ ansible_facts['distribution'] }}.yml"

- name: Install graphics packages
  ansible.builtin.package:
    name: "{{ graphics_packages }}"
    state: present
  tags:
    - packages

