---
- name: Reload systemd config
  ansible.builtin.systemd_service:
    daemon_reload: true
  become: true

- name: Restart resolved
  ansible.builtin.systemd_service:
    name: systemd-resolved.service
    state: restarted

- name: Rebuild grub
  ansible.builtin.command: grub-mkconfig -o /boot/grub/grub.cfg
  become: true
