---
- name: restart_cups
  service:
    name: cups.service
    state: restarted

- name: stop systemd per-user instance
  service:
    name: "user@{{ remote_user.uid }}"
    state: stopped

- name: generate_locales
  ansible.builtin.command: locale-gen
  become: true

- name: reload_systemd_config
  command: systemctl daemon-reload
  become: true

- name: restart_resolved
  service:
    name: systemd-resolved.service
    state: restarted

