---
- name: stop systemd per-user instance
  ansible.builtin.service:
    name: "user@{{ remote_user.uid }}"
    state: stopped

- name: reload_systemd_config
  ansible.builtin.command: systemctl daemon-reload
  become: true

- name: restart_resolved
  ansible.builtin.service:
    name: systemd-resolved.service
    state: restarted

- name: rebuild-grub
  ansible.builtin.command: grub-mkconfig -o /boot/grub/grub.cfg
  become: true

