---
- name: Start 'nextcloud-all-in-one' container
  community.docker.docker_container:
    name:  nextcloud-aio-mastercontainer
    image: nextcloud/all-in-one:latest
    state: started
    restart_policy: unless-stopped
    volumes:
      - nextcloud_aio_mastercontainer:/mnt/docker-aio-config
      - /var/run/docker.sock:/var/run/docker.sock:ro
    published_ports:
      - "80:80"
      - "8080:8080"
      - "8443:8443"
      - "443:443"
    env:
        NEXTCLOUD_ENABLE_DRI_DEVICE: "true"
        # Values which might be parsed as numbers, booleans or other types by the YAML parser need to be quoted
        NEXTCLOUD_UPLOAD_LIMIT: "10G"

- name: Configure Nextcloud firewall exception
  ansible.builtin.copy:
    src: ufw-nextcloud-aio
    dest: /etc/ufw/applications.d/nextcloud-aio
    backup: yes
  notify: restart_ufw

- name: Open Nexcloud ports
  ansible.builtin.command: |
    ufw allow nextcloud-all comment 'Nextcloud all-in-one'
  become: true

