- name: restart_nullmailer
  ansible.builtin.service:
    name: nullmailer.service
    state: restarted

- name: restart_smartd
  ansible.builtin.service:
    name: smartd.service
    state: restarted

- name: restart_sensorsd
  ansible.builtin.service:
    name: "{{ sensors_service }}"
    state: restarted
  when: ansible_facts['virtualization_role'] != "guest"

- name: restart_logwatch
  ansible.builtin.service:
    name: logwatch.timer
    state: restarted
  when: ansible_facts['distribution'] == "Archlinux"
