- name: Restart nullmailer
  ansible.builtin.service:
    name: nullmailer.service
    state: restarted

- name: Restart smartd
  ansible.builtin.service:
    name: smartd.service
    state: restarted

- name: Restart sensorsd
  ansible.builtin.service:
    name: "{{ monitor_sensors_service }}"
    state: restarted
  when: ansible_facts['virtualization_role'] != "guest"

- name: Restart logwatch
  ansible.builtin.service:
    name: logwatch.timer
    state: restarted
  when: ansible_facts['distribution'] == "Archlinux"
