base_packages:
    # - base-devel
    # - man-pages
    # - fwupd
    # - dmidecode
    - tmux
    - rsync
    # - coreutils
    # - moreutils
    # - dateutils
    - linux-firmware
    - nano
    - sudo
    - xdg-user-dirs
    - btrfs-progs
    - man-db
    - ansible
    - efibootmgr
    - zip
    - unzip
    - p7zip
    - unrar
    - pigz
    - dosfstools
    - ntfs-3g
    - exfat-utils
    - rclone
    - which
    - tree
    - cryfs
    - etckeeper
