---
- name: Install firewall
  ansible.builtin.package:
    name: ["ufw"]
    state: present
  tags:
    - packages

- name: Configure Plex firewall exception
  ansible.builtin.copy:
    src: ufw-plexmediacenter
    dest: /etc/ufw/applications.d/plexmediaserver
    owner: root
    mode: "0640"
    backup: true

- name: Increase the number of files non-root users are allowed to subscribe to via inotify
  ansible.builtin.copy:
    src: 40-max-user-watches.conf
    dest: /etc/sysctl.d/40-max-user-watches.conf
    owner: root
    mode: "0640"
    backup: true

- name: Open Plex ports
  community.general.ufw:
    rule: allow
    name: plexmediaserver
    comment: Plex
  become: true
