---
- name: Install firewall
  ansible.builtin.package:
    name: ["ufw"]
    state: present
  tags:
    - packages

- name: Configure Plex firewall exception
  ansible.builtin.copy:
    src: ufw-plexmediacenter
    dest: /etc/ufw/applications.d/plexmediaserver
    backup: yes

- name: Open Plex ports
  community.general.ufw:
    rule: allow
    name: plexmediaserver
    comment: Plex
  become: true

