# - name: Set OS distribution dependent variables
#   ansible.builtin.include_vars: "os_{{ ansible_facts['distribution'] }}.yml"

- name: Install compiling tools
  ansible.builtin.package:
    name:
      - base-devel
      - pigz
      - pbzip2
    state: present
  when: ansible_facts['distribution'] == "Archlinux"

- name: Ensure wheel group exists
  ansible.builtin.group:
    name: wheel
    state: present
  tags:
    - aur
    - packages
  when: ansible_facts['distribution'] == "Archlinux"

- name: Create the `aur_builder` user
  become: true
  ansible.builtin.user:
    name: "{{ aur.builder }}"
    create_home: true
    uid: 1110
    group: wheel
  tags:
    - aur
    - packages
  when: ansible_facts['distribution'] == "Archlinux"

- name: Allow the `aur_builder` user to run `sudo pacman` without a password
  become: true
  ansible.builtin.lineinfile:
    path: /etc/sudoers.d/11-install-aur_builder
    line: "{{ aur.builder }} ALL=(ALL) NOPASSWD: /usr/bin/pacman"
    create: true
    validate: 'visudo -cf %s'
    owner: root
    group: root
    mode: '0640'
  tags:
    - aur
    - packages
  when: ansible_facts['distribution'] == "Archlinux"

- name: Create AUR directory
  ansible.builtin.file:
    path: /home/{{ aur.builder }}/{{ aur.dir }}
    state: directory
    owner: "{{ aur.builder }}"
    group: wheel
    mode: '0750'
  tags:
    - aur
    - packages
  when: ansible_facts['distribution'] == "Archlinux"

- name: Create package configuration directory
  ansible.builtin.file:
    path: /home/{{ aur.builder }}/.config/pacman
    state: directory
    owner: "{{ aur.builder }}"
    group: wheel
    mode: '0750'
  tags:
    - aur
    - packages
  when: ansible_facts['distribution'] == "Archlinux"

- name: Configure software packaging
  ansible.builtin.template:
    src: ../../common/templates/makepkg_conf.j2
    dest: /home/{{ aur.builder }}/.config/pacman/makepkg.conf
    owner: "{{ aur.builder }}"
    group: wheel
    mode: '0640'
    backup: true
  when: ansible_facts['distribution'] == "Archlinux"

- name: Install yay
  kewlfft.aur.aur:
    name:
      - yay
    state: present
    update_cache: "yes"
  tags:
    - aur
    - packages
  become: true
  become_user: "{{ aur.builder }}"
  when: ansible_facts['distribution'] == "Archlinux"

- name: Indicate that aur.yml has already been run
  ansible.builtin.set_fact:
    aur_ran: true
