---
# TODO: Fully deconflict systemd-resolved and avahi-daemon mDNS services

# TODO: Configure mDNS for {{ lan.domain }}

- name: Create resolved.conf directory if it does not exist
  ansible.builtin.file:
    path: /etc/systemd/resolved.conf.d
    state: directory
    mode: '0755'

- name: Stop systemd-resolved mDNS and Link-Local Multicast Name Resolution services
  ansible.builtin.copy:
    content: |
      [Resolve]
      MulticastDNS=no
      LLMNR=no
    dest: /etc/systemd/resolved.conf.d/98-avahi.conf
    mode: '0644'
    backup: no
  notify: restart_resolved

- name: Install NSS module for Multicast DNS name resolution (pacman)
  community.general.pacman:
    update_cache: true
    name: 
      - nss-mdns
      - dbus-python
      - python-gobject
      - gtk3
      - qt5-base
    state: present
  tags:
    - packages
  when: ansible_facts['distribution'] == "Archlinux"

- name: Install NSS module for Multicast DNS name resolution (apt)
  become: true
  ansible.builtin.apt:
    name: libnss-mdns
    state: present
  tags:
    - packages
  when: ansible_facts['distribution'] in ["Debian", "Ubuntu"]

- name: Accept mDNS requests from {{ lan.subnet }}
  community.general.ufw:
    rule: allow
    from_ip: "{{ lan.subnet }}"
    to_port: mdns
    to_ip: "{{ lan0.ip}}"
    comment: mDNS
  become: true

- name: Enable service discovery
  ansible.builtin.service:
    name: avahi-daemon.service
    enabled: yes
    state: started

