- name: Create XDG-compliant skeleton dirs for {{ remote_user.shell }}
  ansible.builtin.file:
    path: /etc/skel/.config/{{ remote_user.shell }}/
    state: directory
    mode: '0755'

- name: Create XDG-compliant skeleton files for {{ remote_user.shell }}_profile 
  ansible.builtin.command: /usr/bin/mv /etc/skel/.{{ remote_user.shell }}_profile /etc/skel/.config/{{ remote_user.shell }}/profile
  args:
    creates: /etc/skel/.config/{{ remote_user.shell }}/profile
    removes: /etc/skel/.{{ remote_user.shell }}_profile
  become: yes

- name: Create XDG-compliant skeleton files for {{ remote_user.shell }}_logout 
  ansible.builtin.command: /usr/bin/mv /etc/skel/.{{ remote_user.shell }}_logout /etc/skel/.config/{{ remote_user.shell }}/logout
  args:
    creates: /etc/skel/.config/{{ remote_user.shell }}/logout
    removes: /etc/skel/.{{ remote_user.shell }}_logout
  become: yes

- name: Create XDG-compliant skeleton files for {{ remote_user.shell }}rc
  ansible.builtin.command: /usr/bin/mv /etc/skel/.{{ remote_user.shell }}rc /etc/skel/.config/{{ remote_user.shell }}/{{ remote_user.shell }}rc
  args:
    creates: /etc/skel/.config/{{ remote_user.shell }}/{{ remote_user.shell }}rc
    removes: /etc/skel/.{{ remote_user.shell }}rc
  become: yes

- name: Create XDG-compliant BASH login shell
  ansible.builtin.copy:
    src: bash_xdg
    dest: /etc/profile.d/bash_xdg.sh
    backup: false
    mode: '0644'
  notify: 

- name: Create XDG-compliant BASH login shell
  ansible.builtin.copy:
    src: bash_xdg
    dest: /etc/skel/.{{ remote_user.shell }}rc
    backup: false
    mode: '0644'
  notify: 

# - name: Create XDG-compliant BASH login shell
#   ansible.builtin.blockinfile:
#     path: /etc/skel/.{{ remote_user.shell }}rc
#     block: | 
#       _confdir=${XDG_CONFIG_HOME:-$HOME/.config}/bash
#       _datadir=${XDG_DATA_HOME:-$HOME/.local/share}/bash

#       [[ -r "$_confdir/bashrc" ]] && . "$_confdir/bashrc"
#       [[ -r "$_confdir/aliases" ]] && . "$_confdir/aliases"

#       [[ ! -d "$_datadir" ]] && mkdir -p "$_datadir"
#       HISTFILE=$_datadir/history

#       unset _confdir
#       unset _datadir
#     insertafter: 'EOF'
#     mode: '0644'
#     backup: true

- name: Set global environment variables
  ansible.builtin.blockinfile:
    path: /etc/security/pam_env.conf
    block: | 
      XDG_CONFIG_DIRS DEFAULT=/etc/xdg
      XDG_DATA_DIRS   DEFAULT=/usr/local/share:/usr/share
      XDG_CONFIG_HOME DEFAULT=@{HOME}/.config
      XDG_CACHE_HOME  DEFAULT=@{HOME}/.cache
      XDG_DATA_HOME   DEFAULT=@{HOME}/.local/share
      XDG_STATE_HOME  DEFAULT=@{HOME}/.local/state
      DIFFPROG        DEFAULT=meld
      EDITOR          DEFAULT=nano
      SUDO_EDITOR     DEFAULT=nano
      VISUAL          DEFAULT=nano
    insertafter: 'EOF'
    mode: '0644'
    backup: true
#   notify: 

