---
- name: Create user group
  ansible.builtin.group:
    name: "{{ remote_user.group }}"
    gid: "{{ remote_user.uid }}"
    state: present
  tags:
    - user

- name: Ensure wheel group exists
  ansible.builtin.group:
    name: wheel
    state: present
  tags:
    - user
  when: ansible_facts['distribution'] == "Archlinux"

- name: Create user and assign to group
  ansible.builtin.user:
    name: "{{ remote_user.name }}"
    group: "{{ remote_user.group }}"
    password: "{{ remote_user.password|password_hash('sha512') }}"
    password_lock: false
    update_password: on_create # --> only set the password for newly created users
    shell: "{{ remote_user.shell_path }}"
    uid: "{{ remote_user.uid }}"
    groups: sys,floppy,users,video,lp,audio,adm,{{ os_groups }}
    append: yes   # --> user is not removed from existing groups
    generate_ssh_key: true
    ssh_key_passphrase: "{{ ssh_key_passphrase }}"
    ssh_key_type: ed25519
    state: present
  tags:
    - user

- name: Allow prime user to run `sudo`
  ansible.builtin.lineinfile:
    path: /etc/sudoers.d/20-primeuser
    line: "{{ remote_user.name }} ALL=(ALL:ALL) ALL"
    create: yes
    validate: 'visudo -cf %s'

- name: Add authorized SSH keys
  ansible.builtin.copy:
    src: authorized_keys
    dest: /home/{{ remote_user.name }}/.ssh/authorized_keys
    owner: "{{ remote_user.name }}"
    group: "{{ remote_user.group }}"
    force: true
    backup: no

- name: Create rclone config directory if it does not exist
  ansible.builtin.file:
    path: /home/{{ remote_user.name }}/.config/rclone
    state: directory
    owner: "{{ remote_user.name }}"
    group: "{{ remote_user.group }}"
    mode: '0700'

- name: Create rclone config
  ansible.builtin.template:
    src: rclone_conf.j2
    dest: /home/{{ remote_user.name }}/.config/rclone/rclone.conf
    owner: "{{ remote_user.name }}"
    group: "{{ remote_user.group }}"
    backup: no
    mode: '600'

- name: Create other config files
  ansible.builtin.copy:
    src: dotfiles/config/
    dest: /home/{{ remote_user.name }}/.config/
    owner: "{{ remote_user.name }}"
    group: "{{ remote_user.group }}"
    backup: yes

