---
- name: Create network bridge
  become: true
  ansible.builtin.copy:
    content: |
      [NetDev]
      Name=br0
      Kind=bridge
      MACAddress={{ lan0.mac }}
    dest: /etc/systemd/network/02-create-bridge-br0.netdev
    backup: true
  notify: [vmhost:systemctl_daemon-reload, vmhost:restart_systemd-networkd]

- name: Bind {{ lan0.ifname }} to network bridge
  become: true
  ansible.builtin.copy:
    content: |
      [Match]
      Name={{ lan0.ifname }}

      [Network]
      Bridge=br0
    dest: /etc/systemd/network/20-bind-ethernet-to-bridge-br0.network
    backup: true
  notify: [vmhost:systemctl_daemon-reload, vmhost:restart_systemd-networkd]

- name: Configure bridge
  become: true
  ansible.builtin.copy:
    content: |
      [Match]
      Name=br0

      [Address]
      Address={{ lan0.ip }}/24

      [Route]
      Gateway={{ lan.gateway }}
      GatewayOnLink=true

      [Network]
      MulticastDNS=yes
      IPMasquerade=yes
      DHCPServer=yes

      [DHCPServer]
      DNS=1.1.1.1 1.0.0.1 208.67.222.222 208.67.220.220
    dest: /etc/systemd/network/25-config-bridge-br0.network
    backup: true
  notify: [vmhost:systemctl_daemon-reload, vmhost:restart_systemd-networkd]

- name: Configure routing between internet facing {{ wan.ifname }} and br0
  become: true
  ansible.builtin.copy:
    content: |
      [Match]
      Name={{ wan.ifname }}

      [Network]
      DHCP=yes
      MulticastDNS=yes
    dest: /etc/systemd/network/04-{{ wan.ifname }}.network
    backup: true
  notify: [vmhost:systemctl_daemon-reload, vmhost:restart_systemd-networkd]

- name: Create custom qemu config allowing {{ remote_user.name }} to connect VM guests to br0
  become: true
  ansible.builtin.copy:
    content: 'allow br0'
    dest: /etc/qemu/{{ remote_user.name }}.conf
    owner: root
    group: "{{ remote_user.group }}"
    mode: '0640'
    backup: true

- name: Source {{ remote_user.name }}'s qemu custom config
  become: true
  ansible.builtin.lineinfile:
    path: /etc/qemu/bridge.conf
    line: include /etc/qemu/{{ remote_user.name }}.conf
    backup: true
