---
- name: Set OS distribution dependent variables
  include_vars: "os_{{ ansible_facts['distribution'] }}.yml"

- name: Install virtualization packages
  ansible.builtin.package:
    name: "{{ virtualization_packages }}"
    state: present
  tags:
    - packages
    - vmhost

# The libvirt group is optional. It is not needed if the user is a member of the wheel group (arch) or sudo group (ubuntu)
- name: Create libvirt group
  ansible.builtin.group:
    name: libvirt
    state: present
  tags:
    - vmhost

- name: Add prime user to libvirt group
  ansible.builtin.command: |
    usermod -a -G libvirt {{ remote_user.name }}
  become: true

- name: Enable and start libvirt
  service:
    name: libvirtd.service
    enabled: yes
    state: started
