- name: Change the DPI to "96"
  become: true
  become_user: "{{ remote_user.name }}"
  community.general.xfconf:
    channel: xsettings
    property: /Xft/DPI
    value_type: int
    value: 96

- name: Customize {{ remote_user.name }}'s wallpaper
  become: true
  become_user: "{{ remote_user.name }}"
  community.general.xfconf:
    channel: xfce4-desktop
    property: /backdrop/screen0/monitorVirtual-1/workspace0/last-image
    value_type: string
    value: /usr/share/backgrounds/xfce/XFCE_83_No_Logo.png
    state: present

- name: Customize {{ remote_user.name }}'s theme
  become: true
  become_user: "{{ remote_user.name }}"
  community.general.xfconf:
    channel: xsettings
    property: /Net/ThemeName
    value_type: string
    value: Gradient-black-46
    state: present

- name: Customize {{ remote_user.name }}'s icons
  become: true
  become_user: "{{ remote_user.name }}"
  community.general.xfconf:
    channel: xsettings
    property: /Net/IconThemeName
    value_type: string
    value: EFDark-IconsCream
    state: present

- name: Load custom actions into {{ remote_user.name }}'s filemanager
  become: true
  become_user: "{{ remote_user.name }}"
  ansible.builtin.command: |
    uca-apply
  become: true

