hostname: archvm

# kernel_parameters: "quiet consoleblank=60"

lan0:
    ip: "{{ lan.base }}.31"
    ifname: enp0s4
    # ip2: "{{ ansible_facts["eth0"]["ipv4"]["address"] }}"

wan:
    ifname: 

ssh_port: 22  # changing this from 22 gets messy. For workaround see https://dmsimard.com/2016/03/15/changing-the-ssh-port-with-ansible/

desktop_environment: kde
