hostname: mintvm

# kernel_parameters: "quiet consoleblank=60"

lan0:
    ip: "{{ lan.base }}.39"
    ifname: 
    mac: 02:00:00:00:01:02

wan:
    ifname: 

ssh_port: 22   # changing this from 22 gets messy. For workaround see https://dmsimard.com/2016/03/15/changing-the-ssh-port-with-ansible/

ntp_enabled: false  # <-- Allow VM host to manage clock
ntp_tinker_panic: true  # <-- Enable tinker panic, which is useful when running NTP in a VM.
