hostname: mythboxtest

# kernel_parameters: "quiet consoleblank=60"

lan0:
    ip: "{{ lan.base }}.94"
    ifname: enp0s4

wan: 
    ifname: 

ssh_port: 22   # changing this from 22 gets messy. For workaround see https://dmsimard.com/2016/03/15/changing-the-ssh-port-with-ansible/
