- name: Install hardening packages
  ansible.builtin.package:
    name: 
      - ufw
      - sshguard
    state: present
  tags:
    - packages

- name: Install endlessh (AUR)
  kewlfft.aur.aur:
    name: 
      - endlessh-git
    state: present
    update_cache: "yes"
  tags:
    - aur
    - packages
  become: true
  become_user: "{{ aur.builder }}"
  when: ansible_facts['distribution'] == "Archlinux"

- name: Configure UFW for sshguard (ipv4)
  ansible.builtin.blockinfile:
    path: /etc/ufw/before.rules
    insertbefore: COMMIT
    block: |
      # hand off control for sshd to sshguard
      :sshguard - [0:0]
      -A ufw-before-input -p tcp --dport "{{ ssh_port }}" -j sshguard
    backup: no

- name: Configure UFW for sshguard (ipv6)
  ansible.builtin.blockinfile:
    path: /etc/ufw/before6.rules
    insertbefore: COMMIT
    block: |
      # hand off control for sshd to sshguard
      :sshguard - [0:0]
      -A ufw6-before-input -p tcp --dport "{{ ssh_port }}" -j sshguard
    backup: no

- name: Enable and start sshguard
  ansible.builtin.service:
    name: sshguard.service
    enabled: yes
    state: started

- name: Open SSH port
  community.general.ufw:
    rule: limit
    to_port: "{{ ssh_port }}"
    proto: tcp
    comment: Rate limit OpenSSH server
  become: true

- name: Open SSH tarpit port
  become: true
  community.general.ufw:
    rule: allow
    to_port: '2222'
    proto: tcp
    comment: OpenSSH tarpit

- name: Open NFS port
  become: true
  community.general.ufw:
    rule: allow
    from_ip: "{{ lan.subnet }}"
    to_ip: "{{ lan0.ip }}"
    to_port: nfs
    comment: NFS

- name: Open phpMyAdmin port
  become: true
  community.general.ufw:
    rule: allow
    from_ip: "{{ lan.subnet }}"
    to_ip: "{{ lan0.ip }}"
    to_port: '51111'
    comment: phpMyAdmin

- name: Open Piwigo ports
  become: true
  community.general.ufw:
    rule: allow
    to_port: '52080'
    comment: Piwigo
