- name: Install hardening packages
  ansible.builtin.package:
    name:
      - ufw
      # - sshguard
    state: present
  tags:
    - packages

- name: Create a directory for custom systemd services
  ansible.builtin.file:
    path: /etc/systemd/system
    state: directory
    owner: root
    group: root
    mode: '0755'

- name: Create custom service file for Endlessh
  ansible.builtin.copy:
    src: endlessh.service
    dest: /etc/systemd/system/endlessh.service
    owner: root
    group: root
    mode: '0644'

- name: Allow Endlessh service to bind on ports lower than 1024
  ansible.builtin.lineinfile:
    path: /etc/systemd/system/endlessh.service
    regexp: 'AmbientCapabilities='
    line: AmbientCapabilities=CAP_NET_BIND_SERVICE
    owner: root
    group: root
    mode: '0644'

- name: Allow Endlessh service to bind on ports lower than 1024
  ansible.builtin.lineinfile:
    path: /etc/systemd/system/endlessh.service
    regexp: 'PrivateUsers='
    line: '#PrivateUsers=true'
    owner: root
    group: root
    mode: '0644'

- name: Install Endlessh (AUR)
  kewlfft.aur.aur:
    name:
      - endlessh-git
    state: present
    update_cache: "yes"
  tags:
    - aur
    - packages
  become: true
  become_user: "{{ aur.builder }}"
  when: ansible_facts['distribution'] == "Archlinux"

- name: Allow Endlessh to run on ports lower than 1024
  ansible.builtin.command: setcap 'cap_net_bind_service=+ep' /usr/bin/endlessh
  become: yes

- name: Have Endlessh listen on port 22
  ansible.builtin.lineinfile:
    path: /etc/endlessh.conf
    regexp: '^Port '
    line: Port 22
    owner: root
    group: root
    mode: '0644'
    create: true

# # Using blockinfile here doesn't work because Ansible can only manage
# # a single block in each file. before.rules already has a managed block
# # in the *nat section of the file for router rules. There is no way to
# # add this sshguard block to the *filter section of before.rules.

# - name: Configure UFW for sshguard (ipv4)
#   ansible.builtin.blockinfile:
#     path: /etc/ufw/before.rules
#     insertbefore: COMMIT
#     block: |
#       # hand off control for sshd to sshguard
#       :sshguard - [0:0]
#       -A ufw-before-input -p tcp --dport "{{ ssh_port }}" -j sshguard
#     backup: true

# - name: Configure UFW for sshguard (ipv6)
#   ansible.builtin.blockinfile:
#     path: /etc/ufw/before6.rules
#     insertbefore: COMMIT
#     block: |
#       # hand off control for sshd to sshguard
#       :sshguard - [0:0]
#       -A ufw6-before-input -p tcp --dport "{{ ssh_port }}" -j sshguard
#     backup: true

# - name: Enable and start sshguard
#   ansible.builtin.service:
#     name: sshguard.service
#     enabled: true
#     state: started

- name: Open SSH port
  community.general.ufw:
    rule: limit
    to_port: "{{ ssh_port }}"
    proto: tcp
    comment: Rate limit OpenSSH server
  become: true

- name: Open SSH tarpit port
  become: true
  community.general.ufw:
    rule: allow
    to_port: '22'
    proto: tcp
    comment: OpenSSH tarpit

# - name: Open NFS port
#   become: true
#   community.general.ufw:
#     rule: allow
#     from_ip: "{{ lan.subnet }}"
#     to_ip: "{{ lan0.ip }}"
#     to_port: nfs
#     comment: NFS

# - name: Open phpMyAdmin port
#   become: true
#   community.general.ufw:
#     rule: allow
#     from_ip: "{{ lan.subnet }}"
#     to_ip: "{{ lan0.ip }}"
#     to_port: "{{ vault_phpmyadmin_port }}"
#     comment: phpMyAdmin

# - name: Open Piwigo port
#   become: true
#   community.general.ufw:
#     rule: allow
#     to_port: "{{ vault_piwigo_port }}"
#     comment: Piwigo
