- name: Set OS distribution dependent variables
  include_vars: "os_{{ ansible_facts['distribution'] }}.yml"

- name: Install hardening packages
  ansible.builtin.package:
    name: 
      - ufw
      - sshguard
      - firejail
    state: present
  tags:
    - packages

- name: Install endlessh (AUR)
  kewlfft.aur.aur:
    name: endlessh-git
    state: present
    update_cache: "yes"
  tags:
    - aur
    - packages
  become: "yes"
  become_user: "{{ aur.builder }}"
  when: ansible_facts['distribution'] == "Archlinux"

- name: Configure UFW for sshguard (ipv4)
  ansible.builtin.blockinfile:
    path: /etc/ufw/before.rules
    insertbefore: COMMIT
    block: |
      # hand off control for sshd to sshguard
      :sshguard - [0:0]
      -A ufw-before-input -p tcp --dport "{{ ssh_port }}" -j sshguard
    backup: no

- name: Configure UFW for sshguard (ipv6)
  ansible.builtin.blockinfile:
    path: /etc/ufw/before6.rules
    insertbefore: COMMIT
    block: |
      # hand off control for sshd to sshguard
      :sshguard - [0:0]
      -A ufw6-before-input -p tcp --dport "{{ ssh_port }}" -j sshguard
    backup: no

- name: Enable and start sshguard
  service:
    name: sshguard.service
    enabled: yes
    state: started

- name: Open SSH port
  community.general.ufw:
    rule: limit
    port: "{{ ssh_port }}"
    proto: tcp
    comment: Rate limit OpenSSH server
    state: enabled
  become: true

- name: Open SSH tarpit port
  become: true
  community.general.ufw:
    rule: allow
    port: '2222'
    proto: tcp
    comment: OpenSSH tarpit
    state: enabled

- name: Open printer administration port
  become: true
  community.general.ufw:
    rule: allow
    from_ip: "{{ lan.subnet }}"
    to_ip: "{{ lan0.ip }}"
    to_port: '631'
    comment: CUPS
    state: enabled

- name: Open NFS port
  become: true
  community.general.ufw:
    rule: allow
    from_ip: "{{ lan.subnet }}"
    to_ip: "{{ lan0.ip }}"
    to_port: nfs
    comment: NFS
    state: enabled

- name: Open phpMyAdmin port
  become: true
  community.general.ufw:
    rule: allow
    from_ip: "{{ lan.subnet }}"
    to_ip: "{{ lan0.ip }}"
    to_port: '51111'
    comment: phpMyAdmin
    state: enabled

- name: Open Piwigo ports
  become: true
  community.general.ufw:
    rule: allow
    to_port: '52080'
    comment: Piwigo
    state: enabled

# PROBABLY NEED TO TEST THIS (e.g. SUBVOLUMES, DOCKER, ETC.) BEFORE ENABLING EVERYTHING.
# - name: Activate firejail
#   ansible.builtin.command: |
#     firecfg
#   become: true
